### ISSUE TITLE
Merge train-student and 8bitdecode guides

### ISSUE THREAD

**Issue by kpu** [browsermt/students#1]
We should have an overall guide for building a student model.  Currently it's fragmented in separate directories and there isn't even a reference.

**Comment by snukky** [comment]
Could you clarify what you would like to have? Moving 8bitdecode/ to the student training instructions as the last, optional step?

**Comment by kpu** [comment]
Yes.

**Comment by XapaJIaMnu** [comment]
About a 10000000 commits later, as I'm distracted. It should be done
