### ISSUE TITLE
CSEN & ENCS best-bleu-detok models are the same

### ISSUE THREAD

**Issue by zouharvi** [browsermt/students#15]
The following two models are the same. Namely, they are both CS->EN.

http://data.statmt.org/bergamot/models/8bit-students/csen/base/model.npz.best-bleu-detok.npz

http://data.statmt.org/bergamot/models/8bit-students/encs/base/model.npz.best-bleu-detok.npz

If they are not used anywhere, that's ok.

**Comment by ugermann** [comment]
Thanks for letting us know. I think the problem has now been fixed.
