### ISSUE TITLE
In corpus cleaning, remove empty lines before predicting language IDs?

### ISSUE THREAD

**Issue by PinzhenChen** [browsermt/students#25]
Perhaps we need to remove empty lines before running [LangID](https://github.com/browsermt/students/blob/eef24ff8b028f47062b633e95807f5dc2c492908/train-student/clean/clean-corpus.sh#L42-L44) in `clean/clean-corpus.sh` otherwise [prediction](https://github.com/browsermt/students/blob/eef24ff8b028f47062b633e95807f5dc2c492908/train-student/clean/tools/langid-fasttext.py#L34-L35) in `clean/tools/langid-fasttext.py` will complain.

**Comment by snukky** [comment]
I think you may feel free to do any modifications improving the script and open a PR.
