### ISSUE TITLE
tcmalloc causes extract_stats.py to crash

### ISSUE THREAD

**Issue by kpu** [browsermt/students#3]
"In very rare cases, the extract_stats.py script might crash. If this happens, the most likely culprit is tcmalloc. If the model is too large (or the workspace too small), tcmalloc will spit tcmalloc: large alloc... to stderr which our script doesn't know how to handle. Just delete that line inside the quantmuls file and you're good to go."

**Comment by XapaJIaMnu** [comment]
I seem to have fixed it at some point: https://github.com/browsermt/marian-dev/blob/master/scripts/alphas/extract_stats.py#L19
