### ISSUE TITLE
Provision of new model(s) for testing multiple model workflows

### ISSUE THREAD

**Issue by jerinphilip** [browsermt/students#43]
Need a few more distinct models to test applications enabled by multiple model capability (https://github.com/browsermt/bergamot-translator/issues/209, https://github.com/browsermt/bergamot-translator/pull/210).

It may be desirable to have something compatible with the forward model. Currently there's an archive from here (`ende.student.tiny.for.regression.tests`) that is kept with separate specs from the usual pool (see https://github.com/browsermt/students/issues/37#issuecomment-842256130). Wouldn't mind having the same spec as the rest of the models here at the cost of discarding file based shortlists etc. 

* One kind of model required is a backward model (`de -> en` for existing `en -> de`) so an outbound translation example can be pointed to in code somewhere and runs on CI everytime (For https://github.com/browsermt/bergamot-translator/issues/78)
* Another kind of model we will soon require is (`xx->en`, `en->yy`) if and when pivoting (https://github.com/browsermt/bergamot-translator/issues/212) comes into the picture.

**Comment by kpu** [comment]
We have en->{et,es,cs} and {et,es,cs}->en.  While I understand that generally we need to improve language support, you already have enough for testing purposes.
