### ISSUE TITLE
Remaining QE Models

### ISSUE THREAD

**Issue by jerinphilip** [browsermt/students#54]
> Location of trained and ready to use quality estimation models for Czech, Spanish, and German. 

From the meeting it appears that a JSON is provided by email and not the binary. The QE team is expected to check-in to this repository, as they did with the English-Estonian model (https://github.com/browsermt/students/pull/44):

1. Binary models converted for the missing languages. 
2. Proper documentation to convert from JSON to binary somewhere. Training information should be a good addition. Refer to https://github.com/browsermt/students/blob/master/train-student/README.md which mentions packaging models for machine-translation and repurpose the structure for QE.

**Comment by kpu** [comment]
Great minds think alike #53

**Comment by jerinphilip** [comment]
Nevermind, duplicate of #53; @kpu beat me to this anyway. Closing in favour of that.
