### ISSUE TITLE
[Question] Training data for the alignment and lexical shortlists?

### ISSUE THREAD

**Issue by ZJaume** [browsermt/students#6]
From where should I train word-alignments an lexical shortlists? From the original parallel corpus or from the distilled data?

**Comment by snukky** [comment]
Word alignments for the guided alignment training need to be generated for the training data specifically. If the goal is to train a student with guided alignment, then it needs to be from the distilled data.

**Comment by ZJaume** [comment]
Ah yes, you are right. Thanks!
